title: 台湾人の永琳
copyright: "Copyright © 2022 台湾人の永琳. All rights reserved."
description: 台湾人の永琳 Official Website
logo: /img/logo.png
email: taiwanese.eirin@gmail.com
sns:
  facebook: https://www.facebook.com/TaiwaneseEirin
  youtube: https://www.youtube.com/c/TaiwaneseEirin_
  plurk: https://www.plurk.com/TaiwaneseEirin
  line: https://lin.ee/2W4EVfJ
  twitch: https://www.twitch.tv/taiwanese_eirin_
  twitter: https://twitter.com/TaiwaneseEirin
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
